//! Siril script generator
//!
//! Generates Siril .ssf scripts from export data and configuration.
//!
//! Phase 4: Updated to use new ExportGroup structure with subgroups
//! and MasterCreationPlan for proper dependency ordering.

use crate::export::folder_structures::SirilFolders;
use crate::export::models::{
    sanitize_folder_name, CameraType, DrizzleScale, ExportConfig, ExportDataV3,
    ImageWeightingMethod, RejectionAlgorithm,
};
use anyhow::{Context, Result};
use std::fs;
use std::path::PathBuf;

// ============================================================================
// Helper Functions for Siril Command Generation
// ============================================================================

/// Build a register command with reference frame selection and optional drizzle
fn build_register_command(config: &ExportConfig, sequence_name: &str) -> String {
    let mut cmd = format!("register {}", sequence_name);

    // Reference frame mode
    match config.reference_frame_mode {
        crate::export::models::ReferenceFrameMode::SirilAuto => {
            cmd.push_str(" -2pass");
        }
        crate::export::models::ReferenceFrameMode::AtheneumScoring => {
            // For now, fall back to -2pass until quality scoring is implemented
            cmd.push_str(" -2pass");
        }
        crate::export::models::ReferenceFrameMode::Manual => {
            // Manual reference frame - would need frame index
            // For now, use -2pass as fallback
            cmd.push_str(" -2pass");
        }
    }

    // Drizzle
    if config.drizzle_enabled {
        cmd.push_str(" -drizzle");
        match config.drizzle_scale {
            DrizzleScale::None => {}
            DrizzleScale::X2 => cmd.push_str(" -scale=2.0"),
            DrizzleScale::X3 => cmd.push_str(" -scale=3.0"),
        }
    }

    cmd
}

// ============================================================================
// V3: Script Generation for Flat Siril Structure
// ============================================================================

/// Convert a list of frame indices to contiguous ranges for Siril select command
///
/// Siril's `select` command takes ranges (from, to), so we need to convert
/// a list like [1,2,3,4,5,51,52,53] into ranges [(1,5), (51,53)]
fn indices_to_ranges(indices: &[usize]) -> Vec<(usize, usize)> {
    if indices.is_empty() {
        return Vec::new();
    }

    let mut sorted: Vec<usize> = indices.to_vec();
    sorted.sort();

    let mut ranges = Vec::new();
    let mut start = sorted[0];
    let mut end = sorted[0];

    for &idx in &sorted[1..] {
        if idx == end + 1 {
            end = idx;
        } else {
            ranges.push((start, end));
            start = idx;
            end = idx;
        }
    }
    ranges.push((start, end));
    ranges
}

/// Generate Siril scripts for V3 export
///
/// Creates three scripts:
/// 1. 00_create_masters.ssf - All masters in dependency order
/// 2. 01_calibrate_lights.ssf - Calibrate all lights by branch
/// 3. 02_register_and_stack.ssf - Register ALL, stack per filter
pub fn generate_scripts_v3(config: &ExportConfig, data: &ExportDataV3) -> Result<Vec<PathBuf>> {
    println!("📝 Generating V3 Siril scripts (flat structure)");
    println!("  Output dir: {:?}", config.output_dir);
    println!("  Branches: {}, Masters: {}", data.branches.len(), data.master_plan.masters.len());

    let folders = SirilFolders::new(config.output_dir.clone());
    let mut scripts = Vec::new();

    // Script 1: Create all masters
    if !data.master_plan.masters.is_empty() && config.create_masters {
        let script = generate_master_script_v4(config, &folders, data)?;
        scripts.push(script);
    }

    // Script 2: Calibrate all lights
    let calibrate_script = generate_calibrate_lights_script_v4(config, &folders, data)?;
    scripts.push(calibrate_script);

    // Script 3: Register ALL lights globally and stack per filter
    // Uses -filter-incl to preserve registration metadata (FWHM, star data) for weighting
    let register_and_stack_script = generate_register_and_stack_script_v4(config, &folders, data)?;
    scripts.push(register_and_stack_script);

    println!("  Generated {} scripts", scripts.len());
    Ok(scripts)
}

// ============================================================================
// V4: Script Generation for Flat Siril Folder Structure
// ============================================================================

/// Generate 00_create_masters.ssf using flat SirilFolders structure
fn generate_master_script_v4(
    config: &ExportConfig,
    folders: &SirilFolders,
    data: &ExportDataV3,
) -> Result<PathBuf> {
    let mut script = String::new();

    script.push_str(&format!(
        r#"############################################
# Siril Master Creation Script (V4 - Flat Structure)
# Generated by Athenaeum
# Total masters: {}
# Cameras: {}
############################################

requires 1.2.0

"#,
        data.master_plan.masters.len(),
        data.cameras.join(", ")
    ));

    // Process masters in dependency order
    for (idx, master) in data.master_plan.masters.iter().enumerate() {
        script.push_str(&format!(
            "# ========== Master {} of {}: {} (Set {}) ==========\n",
            idx + 1,
            data.master_plan.masters.len(),
            master.master_type,
            master.set_id
        ));

        // Work folder path based on master type (flat structure)
        let work_folder = match master.master_type.as_str() {
            "Bias" => folders.bias_set_path(master.set_id),
            "Dark" | "DarkFlat" => folders.dark_set_path(master.set_id),
            "Flat" => {
                // Get filter from first source frame
                let filter = master.source_frames.first().and_then(|f| f.filter.as_deref());
                folders.flat_set_path(master.set_id, filter)
            }
            _ => folders.process.clone(),
        };

        let output_path = folders.masters.join(&master.output_name);
        let type_lower = master.master_type.to_lowercase();

        // Work directly in the set folder
        script.push_str(&format!(
            "cd {}\nconvert {}\n",
            work_folder.to_string_lossy(),
            type_lower
        ));

        // Apply calibrations based on type
        match master.master_type.as_str() {
            "Bias" => {
                script.push_str(&format!(
                    "stack {} rej {} {} -nonorm -out={}\n\n",
                    type_lower,
                    config.rejection_low,
                    config.rejection_high,
                    output_path.to_string_lossy()
                ));
            }
            "Dark" | "DarkFlat" => {
                if let Some(bias_id) = master.apply_bias {
                    let bias_master = folders.masters.join(format!("master_bias_{}", bias_id));
                    script.push_str(&format!(
                        "calibrate {} -bias={}\n",
                        type_lower,
                        bias_master.to_string_lossy()
                    ));
                    script.push_str(&format!(
                        "stack pp_{} rej {} {} -nonorm -out={}\n\n",
                        type_lower,
                        config.rejection_low,
                        config.rejection_high,
                        output_path.to_string_lossy()
                    ));
                } else {
                    script.push_str(&format!(
                        "stack {} rej {} {} -nonorm -out={}\n\n",
                        type_lower,
                        config.rejection_low,
                        config.rejection_high,
                        output_path.to_string_lossy()
                    ));
                }
            }
            "Flat" => {
                // Flat calibration priority:
                // 1. DarkFlat (same exposure as flat) - best
                // 2. Dark with matching exposure (±30%) - good
                // 3. Bias - fallback (minimal subtraction, better than wrong-exposure dark)
                // 4. No calibration - if nothing available
                let mut cal_args = String::new();

                if let Some(darkflat_id) = master.apply_darkflat {
                    // Best: Use DarkFlat (same exposure as flat)
                    let darkflat_master = folders.masters.join(format!("master_darkflat_{}", darkflat_id));
                    cal_args.push_str(&format!(" -dark={}", darkflat_master.to_string_lossy()));
                } else if let Some(dark_id) = master.apply_dark {
                    // Good: Use Dark with matching exposure (apply_dark is only set if exposure matches)
                    let dark_master = folders.masters.join(format!("master_dark_{}", dark_id));
                    cal_args.push_str(&format!(" -dark={}", dark_master.to_string_lossy()));
                } else if let Some(bias_id) = master.apply_bias {
                    // Fallback: Use Bias (minimal subtraction - better than over-subtracting with wrong-exposure dark)
                    // This prevents the bright edges issue caused by using long-exposure darks for short-exposure flats
                    let bias_master = folders.masters.join(format!("master_bias_{}", bias_id));
                    cal_args.push_str(&format!(" -dark={}", bias_master.to_string_lossy()));
                }
                // If nothing available, skip calibration entirely

                if !cal_args.is_empty() {
                    script.push_str(&format!("calibrate flat{}\n", cal_args));
                    script.push_str(&format!(
                        "stack pp_flat rej {} {} -norm=mul -out={}\n\n",
                        config.rejection_low,
                        config.rejection_high,
                        output_path.to_string_lossy()
                    ));
                } else {
                    script.push_str(&format!(
                        "stack flat rej {} {} -norm=mul -out={}\n\n",
                        config.rejection_low,
                        config.rejection_high,
                        output_path.to_string_lossy()
                    ));
                }
            }
            _ => {}
        }
    }

    script.push_str("close\n");

    let script_path = folders.root.join("00_create_masters.ssf");
    fs::write(&script_path, &script)
        .with_context(|| format!("Failed to write master script to {:?}", script_path))?;

    println!("  Created: {:?}", script_path);
    Ok(script_path)
}

/// Generate 01_calibrate_lights.ssf using flat SirilFolders structure
fn generate_calibrate_lights_script_v4(
    config: &ExportConfig,
    folders: &SirilFolders,
    data: &ExportDataV3,
) -> Result<PathBuf> {
    let mut script = String::new();

    script.push_str(&format!(
        r#"############################################
# Siril Light Calibration Script (V4 - Flat Structure)
# Generated by Athenaeum
# Total branches: {}
# Total lights: {}
############################################

requires 1.2.0

"#,
        data.branches.len(),
        data.total_light_frames
    ));

    // Process each branch
    for (idx, branch) in data.branches.iter().enumerate() {
        script.push_str(&format!(
            "# ========== Branch {} of {}: {} ==========\n",
            idx + 1,
            data.branches.len(),
            branch.branch_id
        ));
        script.push_str(&format!("# Camera: {}\n", branch.camera_name));
        script.push_str(&format!(
            "# Filter: {}\n",
            branch.filter.as_deref().unwrap_or("None")
        ));
        script.push_str(&format!("# Lights: {}\n", branch.light_frames.len()));

        // Skip branches with less than 2 lights
        if branch.light_frames.len() < 2 {
            script.push_str("# SKIPPED: Siril requires at least 2 frames\n\n");
            continue;
        }

        script.push_str("\n");

        // Path to lights in flat structure: lights/branch_XX_filter/
        let lights_path = folders.lights_path(branch, idx);

        script.push_str(&format!("cd {}\n", lights_path.to_string_lossy()));
        script.push_str("convert lights\n");

        // Build calibrate command
        let mut cal_args = Vec::new();
        let is_osc = branch.is_osc();

        if branch.dark_id > 0 {
            let dark_master = folders.masters.join(format!("master_dark_{}", branch.dark_id));
            cal_args.push(format!("-dark={}", dark_master.to_string_lossy()));
            cal_args.push("-cc=dark".to_string());
            // Add -cfa for OSC to ensure cosmetic correction respects Bayer pattern
            if is_osc {
                cal_args.push("-cfa".to_string());
            }
        }

        if branch.flat_id > 0 {
            let flat_master = folders.masters.join(format!("master_flat_{}", branch.flat_id));
            cal_args.push(format!("-flat={}", flat_master.to_string_lossy()));
        }

        // OSC debayer - add to calibrate command unless drizzle is enabled
        // With drizzle, we preserve the CFA pattern and debayer happens after drizzle stacking
        if is_osc && !config.drizzle_enabled {
            cal_args.push("-debayer".to_string());
        }

        // Always run calibrate to ensure 32-bit float output (pp_lights_.seq)
        // This is required even without calibration files for consistent bit depth in merge
        // See: https://siril.readthedocs.io/en/latest/Commands.html
        if cal_args.is_empty() {
            script.push_str("calibrate lights\n");
        } else {
            script.push_str(&format!("calibrate lights {}\n", cal_args.join(" ")));
        }

        script.push_str("\n");
    }

    script.push_str("close\n");

    let script_path = folders.root.join("01_calibrate_lights.ssf");
    fs::write(&script_path, &script)
        .with_context(|| format!("Failed to write calibration script to {:?}", script_path))?;

    println!("  Created: {:?}", script_path);
    Ok(script_path)
}

/// Generate 02_register_and_stack.ssf - Astrometric registration and per-group stacking
///
/// Uses the MOSAIC approach which handles different camera dimensions:
/// 1. All calibrated frames are collected to a unified directory (by wrapper script)
/// 2. Convert creates a unified sequence from all frames
/// 3. Plate solving embeds WCS coordinates for astrometric alignment
/// 4. seqapplyreg -framing=max pads smaller frames to match largest
/// 5. Stacks per (filter + camera_type + exptime) group
fn generate_register_and_stack_script_v4(
    config: &ExportConfig,
    folders: &SirilFolders,
    data: &ExportDataV3,
) -> Result<PathBuf> {
    // Use the new astrometric/mosaic approach for all cases
    // This handles different camera dimensions via plate solving + max framing
    generate_astrometric_script_v4(config, folders, data)
}

/// Generate astrometric registration script using dual-pipeline approach
///
/// This approach handles different camera types by processing OSC and Mono
/// frames in SEPARATE pipelines (Siril cannot mix different layer counts):
///
/// For each camera type (if present):
/// 1. Change to camera-specific directory (all_lights_mono or all_lights_osc)
/// 2. Convert to sequence
/// 3. Plate solve for WCS coordinates
/// 4. Apply astrometric registration with -framing=max (pads smaller frames)
/// 5. Stack per (filter + exptime) group
fn generate_astrometric_script_v4(
    config: &ExportConfig,
    folders: &SirilFolders,
    data: &ExportDataV3,
) -> Result<PathBuf> {
    use crate::export::models::GlobalRegistrationPlan;

    let mut script = String::new();

    // Build the registration plan for frame indexing
    let plan = GlobalRegistrationPlan::from_export_data(data);

    // Count frames by camera type
    let mono_branches: Vec<_> = data.branches.iter().filter(|b| !b.is_osc()).collect();
    let osc_branches: Vec<_> = data.branches.iter().filter(|b| b.is_osc()).collect();

    let mono_frames: usize = mono_branches.iter().map(|b| b.light_frames.len()).sum();
    let osc_frames: usize = osc_branches.iter().map(|b| b.light_frames.len()).sum();
    let total_frames = mono_frames + osc_frames;

    let has_mono = mono_frames > 0;
    let has_osc = osc_frames > 0;

    let camera_mode = match (has_osc, has_mono) {
        (true, true) => "DUAL PIPELINE (OSC + Mono)",
        (true, false) => "OSC only",
        (false, true) => "Mono only",
        (false, false) => "Unknown",
    };

    // Get unique camera names for documentation
    let camera_names: Vec<String> = data.branches.iter()
        .map(|b| b.camera_name.clone())
        .collect::<std::collections::HashSet<_>>()
        .into_iter()
        .collect();

    // Get focal length and pixel size for plate solving
    let (focal_length, pixel_size) = get_optics_params(data);

    script.push_str(&format!(
        r#"############################################
# Siril Registration and Stacking Script
# Generated by Athenaeum
#
# DUAL PIPELINE MODE
# OSC and Mono frames processed in separate pipelines
# (Siril cannot mix different layer counts in one sequence)
#
# Camera mode: {}
# Cameras: {}
# Mono frames: {}
# OSC frames: {}
# Total: {} frames
#
# NOTE: Frame collection is handled automatically by Athenaeum
# Frames are separated into all_lights_mono/ and all_lights_osc/
############################################

requires 1.3.0

"#,
        camera_mode,
        camera_names.join(", "),
        mono_frames,
        osc_frames,
        total_frames,
    ));

    // Get stacking groups (grouped by filter + camera_type + exptime)
    let all_stacking_groups = plan.stacking_groups(
        &config.exptime_tolerance_mode,
        config.exptime_tolerance_value,
    );

    // Separate groups by camera type
    let mono_groups: Vec<_> = all_stacking_groups.iter()
        .filter(|g| g.camera_type == CameraType::Mono)
        .collect();
    let osc_groups: Vec<_> = all_stacking_groups.iter()
        .filter(|g| g.camera_type == CameraType::Osc)
        .collect();

    // ==================== MONO PIPELINE ====================
    if has_mono && !mono_groups.is_empty() {
        let mono_dir = folders.process.join("all_lights_mono");

        script.push_str("############################################\n");
        script.push_str("# MONO CAMERA PIPELINE\n");
        script.push_str(&format!("# {} frames from {} branches\n", mono_frames, mono_branches.len()));
        script.push_str("############################################\n\n");

        // Step 1: Change to mono directory and convert
        script.push_str("# --- Step 1: Create Mono Sequence ---\n");
        script.push_str(&format!("cd {}\n", mono_dir.to_string_lossy()));
        script.push_str("convert pp_lights -out=. -fitseq\n\n");

        // Step 2: Plate solve
        script.push_str("# --- Step 2: Plate Solve for WCS ---\n");
        script.push_str(&format!(
            "seqplatesolve pp_lights -focal={:.1} -pixelsize={:.2}\n\n",
            focal_length, pixel_size
        ));

        // Step 3: Register (creates registration transforms using WCS data)
        script.push_str("# --- Step 3: Register Frames ---\n");
        script.push_str("# -2pass auto-selects best reference frame\n");
        script.push_str("# Registration uses WCS data from plate solving\n");
        script.push_str("register pp_lights -2pass\n\n");

        // Step 3b: Convert registered files to sequence
        script.push_str("# --- Step 3b: Create Registered Sequence ---\n");
        script.push_str("# register creates r_pp_lights_*.fit files but no sequence file\n");
        script.push_str("convert r_pp_lights -out=. -fitseq\n\n");

        // Step 4: Stack per group
        script.push_str("# --- Step 4: Stack Per Group ---\n");
        generate_stack_commands_for_groups(
            &mut script,
            config,
            folders,
            &mono_groups,
            mono_frames,
            "r_pp_lights",  // Sequence created by convert above
        );
    }

    // ==================== OSC PIPELINE ====================
    if has_osc && !osc_groups.is_empty() {
        let osc_dir = folders.process.join("all_lights_osc");

        script.push_str("\n############################################\n");
        script.push_str("# OSC CAMERA PIPELINE\n");
        script.push_str(&format!("# {} frames from {} branches\n", osc_frames, osc_branches.len()));
        script.push_str("############################################\n\n");

        // Step 1: Change to OSC directory and convert
        script.push_str("# --- Step 1: Create OSC Sequence ---\n");
        script.push_str(&format!("cd {}\n", osc_dir.to_string_lossy()));
        script.push_str("convert pp_lights -out=. -fitseq\n\n");

        // Step 2: Plate solve
        script.push_str("# --- Step 2: Plate Solve for WCS ---\n");
        script.push_str(&format!(
            "seqplatesolve pp_lights -focal={:.1} -pixelsize={:.2}\n\n",
            focal_length, pixel_size
        ));

        // Step 3: Register (creates registration transforms using WCS data)
        script.push_str("# --- Step 3: Register Frames ---\n");
        script.push_str("# -2pass auto-selects best reference frame\n");
        script.push_str("# Registration uses WCS data from plate solving\n");
        script.push_str("register pp_lights -2pass\n\n");

        // Step 3b: Convert registered files to sequence
        script.push_str("# --- Step 3b: Create Registered Sequence ---\n");
        script.push_str("# register creates r_pp_lights_*.fit files but no sequence file\n");
        script.push_str("convert r_pp_lights -out=. -fitseq\n\n");

        // Step 4: Stack per group
        script.push_str("# --- Step 4: Stack Per Group ---\n");
        generate_stack_commands_for_groups(
            &mut script,
            config,
            folders,
            &osc_groups,
            osc_frames,
            "r_pp_lights",  // Sequence created by convert above
        );
    }

    script.push_str("close\n");

    // Write the main Siril script
    let script_path = folders.root.join("02_register_and_stack.ssf");
    fs::write(&script_path, &script)
        .with_context(|| format!("Failed to write registration/stacking script to {:?}", script_path))?;

    println!("  Created: {:?}", script_path);
    Ok(script_path)
}

/// Generate stack commands for a set of stacking groups
///
/// This generates stack commands for each filter/exptime group within a camera type's pipeline.
/// All frames are registered together (for global alignment), but stacking is done per group
/// using frame selection to pick the right frames for each filter/exptime combination.
///
/// Frame indices come from the calibration branch order, and since filenames are preserved
/// during collection (pp_lights_XXXXX.fit), Siril assigns sequence indices in the same order.
fn generate_stack_commands_for_groups(
    script: &mut String,
    config: &ExportConfig,
    folders: &SirilFolders,
    groups: &[&crate::export::models::ExptimeStackGroup],
    total_frames_in_pipeline: usize,
    registered_sequence_name: &str,
) {
    // Get unique filters for info comment
    let unique_filters: std::collections::HashSet<_> = groups.iter()
        .map(|g| g.filter.as_deref().unwrap_or("Unfiltered"))
        .collect();

    script.push_str(&format!(
        "# Stacking {} groups across {} filter(s): {}\n",
        groups.len(),
        unique_filters.len(),
        unique_filters.iter().cloned().collect::<Vec<_>>().join(", ")
    ));
    script.push_str(&format!("# Total frames in sequence: {}\n\n", total_frames_in_pipeline));

    // Stack each group separately using frame selection
    for group in groups {
        let filter_name = group.filter.as_deref().unwrap_or("Unfiltered");
        let filter_safe = group.filter
            .as_ref()
            .map(|f| sanitize_folder_name(f))
            .unwrap_or_else(|| "unfiltered".to_string());
        let camera_type_str = group.camera_type.display_name().to_lowercase();

        // Skip groups with < 2 frames
        if group.frame_indices.len() < 2 {
            let display_label = format!(
                "{} {} ({} frame)",
                filter_name,
                if group.exptime_display.is_empty() { "" } else { &group.exptime_display },
                group.frame_indices.len()
            );
            script.push_str(&format!(
                "# --- {} - SKIPPED (need >= 2 frames) ---\n\n",
                display_label
            ));
            continue;
        }

        // Build display label with filter and exptime
        let display_label = format!(
            "{} {} ({} frames)",
            filter_name,
            if group.exptime_display.is_empty() { camera_type_str.clone() } else { format!("{} {}", camera_type_str, group.exptime_display) },
            group.frame_indices.len()
        );

        script.push_str(&format!("# --- {} ---\n", display_label));

        // Unselect all frames first
        script.push_str(&format!("unselect {} 1 {}\n", registered_sequence_name, total_frames_in_pipeline));

        // Select only the frames for this group
        let ranges = indices_to_ranges(&group.frame_indices);
        for (start, end) in &ranges {
            script.push_str(&format!("select {} {} {}\n", registered_sequence_name, start, end));
        }

        // Output filename includes filter and exptime
        let output_name = if group.exptime_display.is_empty() {
            format!("{}_{}_stacked", filter_safe, camera_type_str)
        } else {
            format!("{}_{}_{}_stacked", filter_safe, camera_type_str, group.exptime_display)
        };
        let output_path = folders.masters.join(&output_name);

        // Build stack command
        let mut stack_cmd = format!("stack {}", registered_sequence_name);

        // Rejection algorithm
        let rej_cmd = match config.rejection_algorithm {
            RejectionAlgorithm::Percentile => {
                format!(" rej percentile {} {}", config.rejection_low, config.rejection_high)
            }
            RejectionAlgorithm::Sigma => {
                format!(" rej sigma {} {}", config.rejection_low, config.rejection_high)
            }
            RejectionAlgorithm::LinearFit => {
                format!(" rej linear {} {}", config.rejection_low, config.rejection_high)
            }
            RejectionAlgorithm::Gesd => {
                format!(" rej gesd {} {}", config.rejection_low, config.rejection_high)
            }
            RejectionAlgorithm::Mad => {
                format!(" rej mad {} {}", config.rejection_low, config.rejection_high)
            }
        };
        stack_cmd.push_str(&rej_cmd);
        stack_cmd.push_str(" -filter-included");  // Only stack selected frames
        stack_cmd.push_str(" -norm=addscale -output_norm");

        // Image weighting
        match config.image_weighting {
            ImageWeightingMethod::None => {}
            ImageWeightingMethod::Wfwhm => stack_cmd.push_str(" -weight=wfwhm"),
            ImageWeightingMethod::Stars => stack_cmd.push_str(" -weight=nbstars"),
            ImageWeightingMethod::Noise => stack_cmd.push_str(" -weight=noise"),
            ImageWeightingMethod::ExposureTime => stack_cmd.push_str(" -weight=itime"),
        }

        // RGB compositing for OSC cameras
        if group.camera_type == CameraType::Osc {
            stack_cmd.push_str(" -rgb_equal");
        }

        stack_cmd.push_str(&format!(" -out={}", output_path.to_string_lossy()));
        script.push_str(&format!("{}\n\n", stack_cmd));
    }
}

/// Get focal length and pixel size from export data
/// Falls back to reasonable defaults if not available
///
/// Note: Pixel size is not currently stored in ExportFrame, so we use defaults
/// based on common camera sensors. For accurate plate solving, users should
/// ensure FOCALLEN is set in their FITS headers.
fn get_optics_params(data: &ExportDataV3) -> (f64, f64) {
    // Try to get focal length from first branch with valid data
    let mut focal = 0.0;
    for branch in &data.branches {
        if let Some(frame) = branch.light_frames.first() {
            if let Some(f) = frame.focallen {
                if f > 0.0 {
                    focal = f;
                    break;
                }
            }
        }
    }

    // Use defaults if not found
    // Defaults: 500mm focal, 3.76um pixel (common for ASI/QHY cameras)
    if focal <= 0.0 {
        focal = 500.0;
    }

    // Pixel size defaults - common values:
    // ASI2600/QHY268: 3.76um
    // ASI533/QHY533: 3.76um
    // ASI294/QHY294: 4.63um
    // ASI1600/QHY163: 3.8um
    let pixel_size = 3.76;

    (focal, pixel_size)
}

/// Generate script for mixed OSC + Mono camera types (DEPRECATED)
/// Kept for backwards compatibility but now uses astrometric approach
#[allow(dead_code)]
fn generate_mixed_camera_script_v4(
    config: &ExportConfig,
    folders: &SirilFolders,
    data: &ExportDataV3,
) -> Result<PathBuf> {
    let mut script = String::new();

    // Separate branches by camera type
    // Note: Branches with < 2 frames are already handled by the calibration script
    // which creates pp_lights_.seq via seqcpy even for uncalibrated branches
    let osc_branch_indices: Vec<usize> = data.branches.iter()
        .enumerate()
        .filter(|(_, b)| b.is_osc())
        .map(|(i, _)| i)
        .collect();
    let mono_branch_indices: Vec<usize> = data.branches.iter()
        .enumerate()
        .filter(|(_, b)| !b.is_osc())
        .map(|(i, _)| i)
        .collect();

    let osc_frames: usize = osc_branch_indices.iter()
        .map(|&i| data.branches[i].light_frames.len())
        .sum();
    let mono_frames: usize = mono_branch_indices.iter()
        .map(|&i| data.branches[i].light_frames.len())
        .sum();

    script.push_str(&format!(
        r#"############################################
# Siril Registration and Stacking Script
# Generated by Athenaeum
#
# MIXED CAMERA MODE: OSC + Mono cameras detected
# Processing each camera type in separate pipelines
#
# OSC branches: {} ({} frames)
# Mono branches: {} ({} frames)
############################################

requires 1.2.0

cd {}

"#,
        osc_branch_indices.len(), osc_frames,
        mono_branch_indices.len(), mono_frames,
        folders.process.to_string_lossy()
    ));

    // ========== OSC Pipeline ==========
    if !osc_branch_indices.is_empty() {
        script.push_str("############################################\n");
        script.push_str("# OSC CAMERA PIPELINE\n");
        script.push_str("############################################\n\n");

        generate_pipeline_for_camera_type(
            &mut script,
            config,
            folders,
            data,
            &osc_branch_indices,
            "osc",
            true, // is_osc
        )?;
    }

    // ========== Mono Pipeline ==========
    if !mono_branch_indices.is_empty() {
        script.push_str("\n############################################\n");
        script.push_str("# MONO CAMERA PIPELINE\n");
        script.push_str("############################################\n\n");

        generate_pipeline_for_camera_type(
            &mut script,
            config,
            folders,
            data,
            &mono_branch_indices,
            "mono",
            false, // is_osc
        )?;
    }

    script.push_str("close\n");

    let script_path = folders.root.join("02_register_and_stack.ssf");
    fs::write(&script_path, &script)
        .with_context(|| format!("Failed to write registration/stacking script to {:?}", script_path))?;

    println!("  Created: {:?}", script_path);
    Ok(script_path)
}

/// Generate merge/register/stack pipeline for a specific camera type
fn generate_pipeline_for_camera_type(
    script: &mut String,
    config: &ExportConfig,
    folders: &SirilFolders,
    data: &ExportDataV3,
    branch_indices: &[usize],
    camera_suffix: &str,
    is_osc: bool,
) -> Result<()> {
    let seq_name = format!("all_lights_{}", camera_suffix);
    let reg_seq_name = format!("r_all_lights_{}_", camera_suffix);

    // Always start by changing to process folder (important after previous pipeline may have changed CWD)
    script.push_str(&format!("cd {}\n\n", folders.process.to_string_lossy()));

    // Calculate total frames for this camera type
    let total_frames: usize = branch_indices.iter()
        .map(|&i| data.branches[i].light_frames.len())
        .sum();

    // Step 1: Merge (if multiple branches)
    if branch_indices.len() == 1 {
        let branch = &data.branches[branch_indices[0]];
        let lights_path = folders.lights_path(branch, branch_indices[0]);

        // Always use pp_lights_ (calibrate always runs, even without calibration files)
        let local_seq_name = "pp_lights_".to_string();
        let local_reg_seq_name = "r_pp_lights_".to_string();

        script.push_str(&format!("# Single {} branch - no merge needed\n", camera_suffix.to_uppercase()));
        script.push_str(&format!("cd {}\n\n", lights_path.to_string_lossy()));

        // Register
        script.push_str(&format!("# Register {} frames\n", camera_suffix.to_uppercase()));
        let register_cmd = build_register_command(config, &local_seq_name);
        script.push_str(&format!("{}\n", register_cmd));
        script.push_str(&format!("seqapplyreg {} -framing=max\n\n", local_seq_name));

        // Stack
        generate_stacking_for_branches(
            script,
            config,
            folders,
            data,
            branch_indices,
            &local_reg_seq_name,
            total_frames,
            camera_suffix,
            is_osc,
        )?;
    } else {
        // Merge multiple branches
        script.push_str(&format!("# Merge {} branches\n", camera_suffix.to_uppercase()));

        let mut all_sequences: Vec<String> = Vec::new();
        let mut frame_offset = 1;
        for &idx in branch_indices {
            let branch = &data.branches[idx];
            let lights_path = folders.lights_path(branch, idx);

            // Always use pp_lights_ (calibrate always runs, even without calibration files)
            let seq_path = format!("\"{}/pp_lights_\"", lights_path.to_string_lossy());
            all_sequences.push(seq_path);

            let frame_count = branch.light_frames.len();
            script.push_str(&format!(
                "#   {} ({} frames, frames {}-{})\n",
                branch.branch_id,
                frame_count,
                frame_offset,
                frame_offset + frame_count - 1
            ));
            frame_offset += frame_count;
        }

        script.push_str(&format!(
            "\nmerge {} {}\n\n",
            all_sequences.join(" "),
            seq_name
        ));

        // Register
        script.push_str(&format!("# Register {} frames\n", camera_suffix.to_uppercase()));
        let register_cmd = build_register_command(config, &seq_name);
        script.push_str(&format!("{}\n", register_cmd));
        script.push_str(&format!("seqapplyreg {} -framing=max\n\n", seq_name));

        // Stack
        generate_stacking_for_branches(
            script,
            config,
            folders,
            data,
            branch_indices,
            &reg_seq_name,
            total_frames,
            camera_suffix,
            is_osc,
        )?;
    }

    Ok(())
}

/// Generate stacking commands for branches of a specific camera type
fn generate_stacking_for_branches(
    script: &mut String,
    config: &ExportConfig,
    folders: &SirilFolders,
    data: &ExportDataV3,
    branch_indices: &[usize],
    registered_sequence_name: &str,
    total_frames: usize,
    camera_suffix: &str,
    is_osc: bool,
) -> Result<()> {
    script.push_str(&format!("# Stack {} frames by filter\n", camera_suffix.to_uppercase()));

    // Group frames by filter for this camera type
    let mut filter_groups: std::collections::HashMap<Option<String>, Vec<usize>> = std::collections::HashMap::new();
    let mut current_frame = 1;

    for &idx in branch_indices {
        let branch = &data.branches[idx];
        let filter = branch.filter.clone();
        let frame_count = branch.light_frames.len();

        for i in 0..frame_count {
            filter_groups.entry(filter.clone()).or_default().push(current_frame + i);
        }
        current_frame += frame_count;
    }

    // Stack each filter group
    for (filter, frame_indices) in &filter_groups {
        let filter_name = filter.as_deref().unwrap_or("Unfiltered");
        let filter_safe = filter
            .as_ref()
            .map(|f| sanitize_folder_name(f))
            .unwrap_or_else(|| "unfiltered".to_string());

        if frame_indices.len() < 2 {
            script.push_str(&format!(
                "# --- {} ({} frame) - SKIPPED (need >= 2 frames) ---\n\n",
                filter_name, frame_indices.len()
            ));
            continue;
        }

        script.push_str(&format!("# --- {} ({} frames) ---\n", filter_name, frame_indices.len()));

        // Unselect all, then select specific frames
        script.push_str(&format!("unselect {} 1 {}\n", registered_sequence_name, total_frames));
        let ranges = indices_to_ranges(frame_indices);
        for (start, end) in &ranges {
            script.push_str(&format!("select {} {} {}\n", registered_sequence_name, start, end));
        }

        // Output filename with camera suffix
        let output_name = format!("{}_{}_stacked", filter_safe, camera_suffix);
        let output_path = folders.masters.join(&output_name);

        // Build stack command
        let mut stack_cmd = format!("stack {}", registered_sequence_name);

        // Rejection algorithm
        let rej_cmd = match config.rejection_algorithm {
            RejectionAlgorithm::Percentile => {
                format!(" rej percentile {} {}", config.rejection_low, config.rejection_high)
            }
            RejectionAlgorithm::Sigma => {
                format!(" rej sigma {} {}", config.rejection_low, config.rejection_high)
            }
            RejectionAlgorithm::LinearFit => {
                format!(" rej linear {} {}", config.rejection_low, config.rejection_high)
            }
            RejectionAlgorithm::Gesd => {
                format!(" rej gesd {} {}", config.rejection_low, config.rejection_high)
            }
            RejectionAlgorithm::Mad => {
                format!(" rej mad {} {}", config.rejection_low, config.rejection_high)
            }
        };
        stack_cmd.push_str(&rej_cmd);
        stack_cmd.push_str(" -filter-included");
        stack_cmd.push_str(" -norm=addscale -output_norm");

        // Image weighting
        match config.image_weighting {
            ImageWeightingMethod::None => {}
            ImageWeightingMethod::Wfwhm => stack_cmd.push_str(" -weight=wfwhm"),
            ImageWeightingMethod::Stars => stack_cmd.push_str(" -weight=nbstars"),
            ImageWeightingMethod::Noise => stack_cmd.push_str(" -weight=noise"),
            ImageWeightingMethod::ExposureTime => stack_cmd.push_str(" -weight=itime"),
        }

        // RGB compositing for OSC
        if is_osc {
            stack_cmd.push_str(" -rgb_equal");
        }

        stack_cmd.push_str(&format!(" -out={}", output_path.to_string_lossy()));
        script.push_str(&format!("{}\n\n", stack_cmd));
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_indices_to_ranges() {
        assert_eq!(indices_to_ranges(&[]), vec![]);
        assert_eq!(indices_to_ranges(&[1, 2, 3, 4, 5]), vec![(1, 5)]);
        assert_eq!(indices_to_ranges(&[1, 2, 3, 51, 52, 53]), vec![(1, 3), (51, 53)]);
        assert_eq!(indices_to_ranges(&[1, 3, 5, 7]), vec![(1, 1), (3, 3), (5, 5), (7, 7)]);
        assert_eq!(indices_to_ranges(&[10]), vec![(10, 10)]);
    }
}
