//! Siril script templates
//!
//! Contains templates for different Siril processing workflows.

use crate::export::models::SirilWorkflow;

/// Script template configuration
pub struct ScriptTemplate {
    #[allow(dead_code)]
    pub name: &'static str,
    #[allow(dead_code)]
    pub description: &'static str,
    pub template: &'static str,
}

/// Get the script template for a workflow type
pub fn get_template(workflow: &SirilWorkflow) -> ScriptTemplate {
    match workflow {
        SirilWorkflow::MonoPreprocessing => MONO_PREPROCESSING_TEMPLATE,
        SirilWorkflow::OscPreprocessing => OSC_PREPROCESSING_TEMPLATE,
        SirilWorkflow::LrgbProcessing => LRGB_PROCESSING_TEMPLATE,
    }
}

/// Template placeholders:
/// - {working_dir} - Base working directory
/// - {filter} - Filter name (e.g., "Ha", "OIII")
/// - {rejection_low} - Low sigma rejection value
/// - {rejection_high} - High sigma rejection value
/// - {lights_dir} - Directory containing light frames
/// - {darks_dir} - Directory containing dark frames
/// - {flats_dir} - Directory containing flat frames
/// - {bias_dir} - Directory containing bias frames
/// - {masters_dir} - Directory for master calibration frames
/// - {process_dir} - Working directory for processing
/// - {result_dir} - Output directory for final stacked images
/// - {use_bias} - Whether to include bias calibration (0 or 1)
/// - {use_dark_for_flat} - Whether to use dark for flat calibration (0 or 1)

pub const MONO_PREPROCESSING_TEMPLATE: ScriptTemplate = ScriptTemplate {
    name: "Mono Preprocessing",
    description: "Process monochrome or narrowband images per filter",
    template: r#"############################################
# Siril Preprocessing Script - {filter}
# Generated by Athenaeum
############################################

requires 1.2.0

# Set working directory
cd {working_dir}

# ========================================
# Step 1: Create Master Bias (if available)
# ========================================
{bias_section}

# ========================================
# Step 2: Create Master Dark
# ========================================
{dark_section}

# ========================================
# Step 3: Create Master Flat
# ========================================
{flat_section}

# ========================================
# Step 4: Calibrate Light Frames
# ========================================
cd {lights_dir}
convert lights -out={process_dir}
cd {process_dir}
{calibrate_lights_cmd}

# ========================================
# Step 5: Register Light Frames
# ========================================
register pp_lights

# ========================================
# Step 6: Stack Light Frames
# ========================================
stack r_pp_lights rej {rejection_low} {rejection_high} -norm=addscale -output_norm -out={result_dir}/{filter}_stacked

close
"#,
};

pub const OSC_PREPROCESSING_TEMPLATE: ScriptTemplate = ScriptTemplate {
    name: "OSC Preprocessing",
    description: "Process one-shot color camera images",
    template: r#"############################################
# Siril OSC Preprocessing Script
# Generated by Athenaeum
############################################

requires 1.2.0

# Set working directory
cd {working_dir}

# ========================================
# Step 1: Create Master Bias (if available)
# ========================================
{bias_section}

# ========================================
# Step 2: Create Master Dark
# ========================================
{dark_section}

# ========================================
# Step 3: Create Master Flat
# ========================================
{flat_section}

# ========================================
# Step 4: Calibrate Light Frames
# ========================================
cd {lights_dir}
convert lights -out={process_dir}
cd {process_dir}
{calibrate_lights_cmd}

# ========================================
# Step 5: Register Light Frames
# ========================================
# Note: Debayering is handled by -debayer flag in calibrate command above
register pp_lights

# ========================================
# Step 6: Stack Light Frames
# ========================================
stack r_pp_lights rej {rejection_low} {rejection_high} -norm=addscale -output_norm -rgb_equal -out={result_dir}/OSC_stacked

close
"#,
};

pub const LRGB_PROCESSING_TEMPLATE: ScriptTemplate = ScriptTemplate {
    name: "LRGB Processing",
    description: "Combine LRGB filters into color image",
    template: r#"############################################
# Siril LRGB Combination Script
# Generated by Athenaeum
#
# This script assumes individual L, R, G, B
# channels have already been preprocessed
# and stacked.
############################################

requires 1.2.0

cd {result_dir}

# Load stacked channels
# Note: Adjust filenames to match your stacked outputs
load L_stacked
save luminance

load R_stacked
save red

load G_stacked
save green

load B_stacked
save blue

# Create RGB composite
rgbcomp red green blue -out=RGB_composite

# Apply luminance
load luminance
load RGB_composite
# Note: LRGB combination typically done in post-processing
# This creates the components for external combination

close
"#,
};

/// Bias section template (when bias frames are available)
pub const BIAS_SECTION_TEMPLATE: &str = r#"cd {bias_dir}
convert bias -out={process_dir}
cd {process_dir}
stack bias rej 3 3 -nonorm -out={masters_dir}/master_bias"#;

/// Bias section when not available
pub const BIAS_SECTION_EMPTY: &str = "# No bias frames available - skipping bias calibration";

/// Dark section template
pub const DARK_SECTION_TEMPLATE: &str = r#"cd {darks_dir}
convert darks -out={process_dir}
cd {process_dir}
stack darks rej 3 3 -nonorm -out={masters_dir}/master_dark"#;

/// Dark section with bias optimization
pub const DARK_SECTION_WITH_BIAS_TEMPLATE: &str = r#"cd {darks_dir}
convert darks -out={process_dir}
cd {process_dir}
calibrate darks -bias={masters_dir}/master_bias
stack pp_darks rej 3 3 -nonorm -out={masters_dir}/master_dark"#;

/// Dark section when not available
pub const DARK_SECTION_EMPTY: &str = "# No dark frames available - skipping dark calibration";

/// Flat section template
pub const FLAT_SECTION_TEMPLATE: &str = r#"cd {flats_dir}
convert flats -out={process_dir}
cd {process_dir}
calibrate flats -dark={masters_dir}/master_dark
stack pp_flats rej 3 3 -norm=mul -out={masters_dir}/master_flat"#;

/// Flat section with bias only (no dark)
pub const FLAT_SECTION_BIAS_ONLY_TEMPLATE: &str = r#"cd {flats_dir}
convert flats -out={process_dir}
cd {process_dir}
calibrate flats -bias={masters_dir}/master_bias
stack pp_flats rej 3 3 -norm=mul -out={masters_dir}/master_flat"#;

/// Flat section when not available
pub const FLAT_SECTION_EMPTY: &str = "# No flat frames available - skipping flat field correction";

/// Light calibration command with all calibrations
pub const CALIBRATE_LIGHTS_FULL: &str =
    "calibrate pp_lights -dark={masters_dir}/master_dark -flat={masters_dir}/master_flat -cc=dark";

/// Light calibration with dark only
pub const CALIBRATE_LIGHTS_DARK_ONLY: &str =
    "calibrate pp_lights -dark={masters_dir}/master_dark -cc=dark";

/// Light calibration with flat only
pub const CALIBRATE_LIGHTS_FLAT_ONLY: &str =
    "calibrate pp_lights -flat={masters_dir}/master_flat";

/// Light calibration with no calibration files
pub const CALIBRATE_LIGHTS_NONE: &str =
    "# No calibration files available - lights not calibrated";

// OSC variants - include -debayer flag for one-shot color cameras
/// Light calibration command with all calibrations (OSC - includes debayer)
pub const CALIBRATE_LIGHTS_FULL_OSC: &str =
    "calibrate pp_lights -dark={masters_dir}/master_dark -flat={masters_dir}/master_flat -cc=dark -debayer";

/// Light calibration with dark only (OSC - includes debayer)
pub const CALIBRATE_LIGHTS_DARK_ONLY_OSC: &str =
    "calibrate pp_lights -dark={masters_dir}/master_dark -cc=dark -debayer";

/// Light calibration with flat only (OSC - includes debayer)
pub const CALIBRATE_LIGHTS_FLAT_ONLY_OSC: &str =
    "calibrate pp_lights -flat={masters_dir}/master_flat -debayer";

/// Light calibration with no calibration files (OSC - debayer only)
pub const CALIBRATE_LIGHTS_NONE_OSC: &str =
    "calibrate pp_lights -debayer";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_template_selection() {
        let mono = get_template(&SirilWorkflow::MonoPreprocessing);
        assert_eq!(mono.name, "Mono Preprocessing");

        let osc = get_template(&SirilWorkflow::OscPreprocessing);
        assert_eq!(osc.name, "OSC Preprocessing");

        let lrgb = get_template(&SirilWorkflow::LrgbProcessing);
        assert_eq!(lrgb.name, "LRGB Processing");
    }

    #[test]
    fn test_template_contains_placeholders() {
        let template = get_template(&SirilWorkflow::MonoPreprocessing);
        assert!(template.template.contains("{working_dir}"));
        assert!(template.template.contains("{filter}"));
        assert!(template.template.contains("{rejection_low}"));
        assert!(template.template.contains("{rejection_high}"));
    }
}
