// Hand-written TypeScript material with no Rust source, plus small helper
// functions/consts that used to live inline in the 6 files now generated by
// crates/athenaeum-core/src/ts_export.rs (see .superpowers/sdd/p1-ts-inventory.md
// for the full TS-ONLY classification — 68 declarations, all relocated here).
//
// Also carries `...Values` companion objects for former TS `enum`s that are
// referenced as VALUES elsewhere in the frontend (`ImageType`, `MatchMode`,
// `MasterPreference`) — ts-rs derives string-literal unions, not TS enums, so
// there is no runtime object to reference (`ImageType.Light` no longer
// exists; use `ImageTypeValues.Light`). Values are copied verbatim from the
// generated unions in ./models and ./calibration-config, not from memory.
//
// Import direction is one-way: this file imports types FROM the generated
// files below, never the reverse.

import type {
  ImageType,
  FileWithFrame,
  FramesSet,
  FrameCalibrationStatus,
  ScanRoot,
  CalendarMonthData,
} from './models';
import type { ArchiveCompression, FrameRole } from './archive';
import type { MatchMode, ParameterConfig, MasterPreference } from './calibration-config';
import type { AutofindStatus } from './plate-solve';
import type { AnalysisConfig, AnnotationSettings } from './analysis-config';

// ============================================================================
// models.ts TS-ONLY material
// ============================================================================

export interface BlackholeChangedEvent {
  file_id: number;
  action: 'blackholed' | 'restored';
}

// Result of the `check_for_updates` command. Fields are snake_case to match
// the Rust command's serialization (see athenaeum-tauri commands::core).
export interface UpdateInfo {
  current_version: string;
  latest_version: string;
  is_update_available: boolean;
  download_url: string;
}

/** Companion object for the generated `ImageType` string-literal union
 *  (models.rs `ImageType`, serde default variant naming — no rename_all).
 *  Variant strings copied from the generated `models.ts` union, which added
 *  `MasterLight` since the old hand-written enum was last updated. */
export const ImageTypeValues = {
  Light: 'Light',
  Dark: 'Dark',
  Flat: 'Flat',
  Bias: 'Bias',
  DarkFlat: 'DarkFlat',
  MasterLight: 'MasterLight',
  MasterDark: 'MasterDark',
  MasterFlat: 'MasterFlat',
  MasterBias: 'MasterBias',
  MasterDarkFlat: 'MasterDarkFlat',
} as const satisfies Record<string, ImageType>;

// Helper function to check if an imagetyp is a master type
export function isMasterType(imagetyp: ImageType | string): boolean {
  return (
    imagetyp === ImageTypeValues.MasterDark ||
    imagetyp === ImageTypeValues.MasterFlat ||
    imagetyp === ImageTypeValues.MasterBias ||
    imagetyp === ImageTypeValues.MasterDarkFlat
  );
}

export interface Day {
  id: number | null;
  date: string; // ISO 8601 date (YYYY-MM-DD)
  frame_count: number;
}

export interface Setup {
  id: number | null;
  telescop: string | null;
  instrume: string | null;
  filter: string | null;
  binning: string | null;
  gain: number | null;
}

export interface CalibrationSet {
  id: number | null;
  imagetyp: ImageType;
  exptime: number | null;
  filter: string | null;
  ccd_temp: number | null;
  gain: number | null;
  binning: string | null;
  instrume: string | null;
  date: string;
  frame_ids: number[];
}

export interface Tag {
  id: number | null;
  name: string;
  color: string | null;
}

export interface FrameTag {
  frame_id: number;
  tag_id: number;
}

export interface ScanRootWithAvailability extends ScanRoot {
  is_available: boolean;
}

export interface ExportTemplate {
  id: number | null;
  name: string;
  template: string;
  description: string | null;
}

// ── Duplicates picker rule chain ─────────────────────────────────────────────
//
// The duplicates view auto-marks files for deletion using an ordered chain of
// rules. Each rule either picks a deletion set for a group or abstains; the
// first non-abstaining rule wins per group. A rule that would mark every file
// in a group also abstains (safety) so we never produce a group with no
// keepers.

export type RuleKind =
  | 'master_root'
  | 'path_contains'
  | 'oldest_mtime'
  | 'shortest_path';

interface BaseRule {
  enabled: boolean;
}

export interface MasterRootRule extends BaseRule {
  kind: 'master_root';
  config: { rootId: number | null };
}

export interface PathContainsRule extends BaseRule {
  kind: 'path_contains';
  config: { patterns: string[]; caseSensitive: boolean };
}

export interface OldestMtimeRule extends BaseRule {
  kind: 'oldest_mtime';
  config: Record<string, never>;
}

export interface ShortestPathRule extends BaseRule {
  kind: 'shortest_path';
  config: Record<string, never>;
}

export type Rule =
  | MasterRootRule
  | PathContainsRule
  | OldestMtimeRule
  | ShortestPathRule;

export type RuleChain = Rule[];

// DTOs for Tauri commands
export interface ScanResult {
  files_found: number;
  files_processed: number;
  files_skipped: number;
  errors: string[];
  // Frame type counts
  lights_count: number;
  darks_count: number;
  flats_count: number;
  bias_count: number;
  darkflats_count: number;
  // Calibration sets created
  calibration_sets_created: number;
  // Unique camera reconciliation stats (non-zero when instrume suffix state changed during rescan)
  frames_renamed: number;
  calibration_sets_deleted: number;
  sessions_updated: number;
  // Whether scan was cancelled by user
  cancelled: boolean;
}

export interface DirectoryContents {
  subdirectories: string[];
  files: FileWithFrame[];
}

export interface Project {
  id: number | null;
  name: string;
}

export interface FramesSetMember {
  frames_set_id: number;
  frame_id: number;
}

export interface FitsHeader {
  id: number | null;
  file_id: number;
  header: string;
}

// Frame Sets DTOs
export interface AutoGenerateResult {
  sets_created: number;
  frames_clustered: number;
  frames_excluded: number;
  frames_already_in_sets: number;
  exclusion_reasons: string[];
}

export interface FramesSetWithCount {
  frames_set: FramesSet;
  member_count: number;
}

export interface SessionWithMetadata {
  id: number | null;
  imaging_night_id: number;
  instrume: string;
  frame_count: number;
  total_exp_time: number | null;
  created_at: string | null;
  start_date: string | null;
  end_date: string | null;
  avg_ra: string | null;
  avg_dec: string | null;
}

export interface SessionMember {
  session_id: number;
  frame_id: number;
}

// FITS Image Data for Blink Viewer
export interface FitsImageData {
  image_base64: string;
  width: number;
  height: number;
  is_color: boolean;
  bit_depth: number;
}

// Missing file record with status from the database
export interface MissingFileRecord {
  id: number;
  file_id: number;
  scan_root_id: number;
  detected_at: string;
  last_checked_at: string;
  status: 'missing' | 'ignored';
  // File info
  path: string;
  filename: string;
  size: number;
  modified_at: string;
  // Frame info (if exists)
  has_frame: boolean;
  object: string | null;
  date_obs: string | null;
}

// Frame Set Refresh
export interface SetUpdateReport {
  set_id: number;
  set_name: string;
  frames_added: number;
  nights_created: number;
  nights_updated: number;
  frame_ids_added: number[];
  frame_names_added: string[];
}

export interface RefreshResult {
  frames_added: number;
  sets_updated: SetUpdateReport[];
  frames_unassigned: number;
}

export interface CalibrationMatchResult {
  frames_processed: number;
  frames_with_calibration: number;
  frames_partial_calibration: number;
  frames_no_calibration: number;
  sets_linked: number;
  warnings_count: number;
  processing_time_ms: number;
  frame_statuses: FrameCalibrationStatus[];
}

export interface FilterPeriod {
  filter: string | null;
  start_time: string; // ISO 8601 datetime
  end_time: string; // ISO 8601 datetime
  frame_count: number;
}

export interface CalendarYearData {
  year: number;
  months: CalendarMonthData[]; // Only months with data
  totalFrameCount: number;
  totalExposureSeconds: number;
}

/** Result of reclassifying excluded frames */
export interface ReclassifyResult {
  frames_updated: number;
  cameras_refreshed: string[];
}

/** Result of batch frame set analysis */
export interface AnalyzeFrameSetResult {
  analyzed: number;
  skipped: number;
  failed: number;
  errors: string[];
  cancelled: boolean;
}

/** Analysis progress event emitted during batch analysis */
export interface AnalysisProgressEvent {
  frame_set_id: number;
  current: number;
  total: number;
  current_file: string;
  percent: number;
}

/** Analysis complete event emitted when a frame set analysis finishes */
export interface AnalysisCompleteEvent {
  frame_set_id: number;
  analyzed: number;
  skipped: number;
  failed: number;
  errors: string[];
  cancelled: boolean;
}

/** Registration status for a single frame. Note: the generated
 *  `RegistrationRecord.status` / `StackingPrepProgressEvent.status` fields
 *  are plain `string` (Rust field type is `String`, not an enum), so this
 *  narrower literal union is no longer structurally enforced there — kept
 *  here for call sites that still want the documented value set. */
export type FrameRegistrationStatus =
  | 'pending'
  | 'aligning'
  | 'aligned'
  | 'aligned_flipped'
  | 'reference'
  | 'failed';

/** Response from `compute_flat_contour_plot`. The `pixelsB64` field is the
 *  final 8-bit grayscale display image (length == width*height) base64-
 *  encoded for JSON transport. The frontend paints those bytes directly
 *  via putImageData; the legend strip is built from `minQuantile`,
 *  `maxQuantile`, and `contours`. */
export interface FlatContourPlot {
  width: number;
  height: number;
  /** Raw-units peak of the resampled, pre-rescale image. */
  peak: number;
  /** Raw-units mean. */
  mean: number;
  /** Raw-units min. */
  min: number;
  /** 1st-percentile sample value (legend low edge, original flat units). */
  minQuantile: number;
  /** 99th-percentile sample value (legend high edge, original flat units). */
  maxQuantile: number;
  /** Echoed back from the request — number of bands the result uses. */
  contours: number;
  /** Base64-encoded 8-bit grayscale buffer. */
  pixelsB64: string;
}

// ============================================================================
// archive.ts TS-ONLY material
// ============================================================================

export interface ArchiveSettings {
  rootPath: string | null;
  compression: ArchiveCompression;
}

export interface ArchivedFrameSetSummary {
  frames_set_id: number;
  name: string | null;
  archived_at: string | null;
  operation_id: number | null;
  archive_root_path: string | null;
  started_at: string | null;
  lights_count: number;
  flats_count: number;
  darks_count: number;
  bias_count: number;
  darkflats_count: number;
}

export interface ArchiveProgressEvent {
  operation_id: number;
  stage: string;
  current: number;
  total: number;
  message: string;
}

export interface ArchiveRoot {
  id: number;
  path: string;
  label: string | null;
  is_default: boolean;
}

export interface ArchiveZip {
  path: string;
  filename: string;
  frame_role: FrameRole | string;
  exists: boolean;
  size_bytes: number;
}

// ============================================================================
// export.ts TS-ONLY material
// ============================================================================

/** Frame set summary for export selection */
export interface ExportableFrameSet {
  id: number;
  name: string | null;
  totalExposureSeconds: number;
  frameCount: number;
  objectName: string | null;
  filters: string[];
}

// ============================================================================
// calibration-config.ts TS-ONLY material
// ============================================================================

/** Companion object for the generated `MatchMode` string-literal union
 *  (calibration/config.rs `MatchMode`, serde `rename_all = "lowercase"`). */
export const MatchModeValues = {
  Exact: 'exact',
  Warning: 'warning',
  Ignore: 'ignore',
} as const satisfies Record<string, MatchMode>;

/** Companion object for the generated `MasterPreference` string-literal union
 *  (calibration/config.rs `MasterPreference`, serde `rename_all = "snake_case"`). */
export const MasterPreferenceValues = {
  PreferMaster: 'prefer_master',
  PreferFrameset: 'prefer_frameset',
  NoPreference: 'no_preference',
} as const satisfies Record<string, MasterPreference>;

/** Helper to create a default ParameterConfig */
export function createParameterConfig(
  mode: MatchMode = MatchModeValues.Ignore,
  options: {
    required?: boolean;
    warning_threshold?: number;
    matching_threshold?: number;
    locked?: boolean;
    supports_warning?: boolean;
  } = {}
): ParameterConfig {
  return {
    mode,
    required: options.required ?? false,
    warning_threshold: options.warning_threshold,
    matching_threshold: options.matching_threshold,
    locked: options.locked ?? false,
    supports_warning: options.supports_warning ?? false,
  };
}

/** Helper to create exact match config (can be changed to ignore) */
export function exactMatch(required: boolean = true): ParameterConfig {
  return {
    mode: MatchModeValues.Exact,
    required,
    locked: false,
    supports_warning: false,
  };
}

/** Helper to create warning match config with dual thresholds */
export function warningMatch(
  warningThreshold: number,
  matchingThreshold: number
): ParameterConfig {
  return {
    mode: MatchModeValues.Warning,
    required: false,
    warning_threshold: warningThreshold,
    matching_threshold: matchingThreshold,
    locked: false,
    supports_warning: true,
  };
}

/** Helper to create ignore config */
export function ignoreParam(): ParameterConfig {
  return {
    mode: MatchModeValues.Ignore,
    required: false,
    locked: false,
    supports_warning: false,
  };
}

/** Helper to create ignore config that supports warning mode */
export function ignoreWithWarningSupport(): ParameterConfig {
  return {
    mode: MatchModeValues.Ignore,
    required: false,
    locked: false,
    supports_warning: true,
  };
}

/** Validate that warning_threshold <= matching_threshold */
export function validateThresholds(config: ParameterConfig): string | null {
  if (config.mode === MatchModeValues.Warning) {
    const warn = config.warning_threshold ?? 0;
    const match = config.matching_threshold ?? Infinity;
    if (warn > match) {
      return `Warning threshold (${warn}) cannot be greater than matching threshold (${match})`;
    }
  }
  return null;
}

/** Get display label for a parameter */
export function getParameterLabel(param: string): string {
  const labels: Record<string, string> = {
    instrume: "Camera",
    binning: "Binning",
    gain: "Gain",
    offset: "Offset",
    telescop: "Telescope",
    exptime: "Exposure",
    focallen: "Focal Length",
    filter: "Filter",
    ccd_temp: "CCD Temp",
  };
  return labels[param] || param;
}

/** Parameters that can be exact or disabled (no warning mode) */
export const EXACT_OR_DISABLED_PARAMETERS = [
  "instrume",
  "binning",
  "gain",
  "offset",
  "telescop",
  "filter",
] as const;

/** Parameters that support warning mode with dual thresholds */
export const WARNING_CAPABLE_PARAMETERS = [
  "exptime",
  "focallen",
  "ccd_temp",
] as const;

/** All configurable parameters */
export const CONFIGURABLE_PARAMETERS = [
  "instrume",
  "binning",
  "gain",
  "offset",
  "telescop",
  "exptime",
  "focallen",
  "filter",
  "ccd_temp",
] as const;

export type ConfigurableParameter = (typeof CONFIGURABLE_PARAMETERS)[number];
export type ExactOrDisabledParameter =
  (typeof EXACT_OR_DISABLED_PARAMETERS)[number];
export type WarningCapableParameter =
  (typeof WARNING_CAPABLE_PARAMETERS)[number];

/** Check if a parameter supports warning mode */
export function supportsWarningMode(
  param: string
): param is WarningCapableParameter {
  return (WARNING_CAPABLE_PARAMETERS as readonly string[]).includes(param);
}

/** Check if a parameter is exact-or-disabled (no warning mode) */
export function isExactOrDisabled(
  param: string
): param is ExactOrDisabledParameter {
  return (EXACT_OR_DISABLED_PARAMETERS as readonly string[]).includes(param);
}

// ============================================================================
// plate-solve.ts TS-ONLY material
// ============================================================================

export interface PlateSolveProgressEvent {
  frame_id: number;
  current: number;
  total: number;
  status: "solving" | "solved" | "failed";
  matched_stars?: number;
  rms_arcsec?: number;
  error?: string;
  /** Machine code for a failure (solvemyastro FailureClass, e.g. "VERIFY_GAP",
   * or "REJECTED_LOW_CONFIDENCE" / "PANIC"). Lets the UI group/style reasons. */
  failure_code?: string;
  /** Frame filename, for labelling per-frame rows without a separate lookup. */
  filename?: string;
}

export interface PlateSolveCompleteEvent {
  solved: number;
  failed: number;
  total: number;
  total_time_ms: number;
}

export interface CatalogStatusInfo {
  name: string;
  density: number;
  installed: boolean;
  epoch: number;
  star_count_approx: number;
  size_bytes: number;
  min_fov_deg: number;
  mag_limit: number;
}

export interface CatalogDownloadProgress {
  phase: 'tier' | 'downloading' | 'verifying' | 'extracting' | 'complete' | 'error';
  current: number;
  total: number;
  percent: number;
  tierDensity: number;
  tierIndex: number;
  nTiers: number;
}

export interface AutofindProgressEvent {
  frame_id: number;
  current: number;
  total: number;
  status: AutofindStatus;
  designation: string | null;
  distance_deg: number | null;
  /** "contains" or "nearest" when status === "labeled"; null otherwise. */
  reason: "contains" | "nearest" | null;
  /** Frame's RA/Dec at the moment of the lookup, if available. */
  frame_ra: number | null;
  frame_dec: number | null;
  /** On status === "no_match", the designation of the nearest DSO regardless
   *  of tolerance. Populated so the UI can explain why the match failed
   *  ("closest was M 31 at 0.38°, outside 0.2° tolerance"). */
  closest_designation: string | null;
  closest_distance_deg: number | null;
}

export interface AutofindCompleteEvent {
  total: number;
  labeled: number;
  no_match: number;
  already_labeled: number;
  missing_coords: number;
  errors: number;
  cancelled: boolean;
  total_time_ms: number;
}

// ============================================================================
// analysis-config.ts TS-ONLY material
// ============================================================================

/** Default analysis configuration values */
export const DEFAULT_ANALYSIS_CONFIG: AnalysisConfig = {
  detection_sigma: 5.0,
  min_star_area: 5,
  max_star_area: 2000,
  saturation_fraction: 0.95,
  max_stars: 500,
  trail_threshold: 0.5,
  mrs_layers: 0,
  measure_cap: 2000,
  fit_max_iter: 25,
  fit_tolerance: 1e-4,
  fit_max_rejects: 5,
  batch_concurrency: 3,
};

/** Default annotation settings matching rustafits defaults */
export const DEFAULT_ANNOTATION_SETTINGS: AnnotationSettings = {
  color_scheme: 'eccentricity',
  show_direction_tick: true,
  min_radius: 6.0,
  max_radius: 60.0,
  line_width: 2,
  ecc_good: 0.5,
  ecc_warn: 0.6,
  fwhm_good: 1.3,
  fwhm_warn: 2.0,
};
